Repository Air-Clean/airclean-spring, pull requests merged in 2024-08, with the labels that each got.

#119 [feature] branch 완료
  src/main/java/aircleanprojectback/restapi/branch/repository/BranchRepository.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/controller/BranchController.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/service/BranchService.java
  src/main/resources/static/memberimgs/2b76defc3ce34dcbb4b45ec51c1e7d27.png
  src/main/resources/static/memberimgs/55c32a9230ec49809b49a69abf0910a4.png
  src/main/resources/static/memberimgs/b776a0bad37c408e8bc978b12a58e364.png
  src/main/resources/static/memberimgs/cf0b1da3e9784427931b4d12825e2719.png
  src/main/resources/static/memberimgs/e638b00402b4462493e8e6f3f240f528.png
  src/main/resources/static/memberimgs/e9e75d4bddd5493da332a1103caa090e.png
Labels: ✨Feature

#123 [FEATURE]지점장페이지/ 보고서조회 - 매출보고서 수정
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/dto/BranchSalesDTO.java
  src/main/java/aircleanprojectback/restapi/report/entity/BranchSales.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
Labels: ✨Feature, 📫API

#126 [feature] driver 관련 entity 생성
  src/main/java/aircleanprojectback/restapi/branchOrigin/dto/BranchPageDTO.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/dto/MembersPageDTO.java
  src/main/java/aircleanprojectback/restapi/car/dto/CarDTO.java
  src/main/java/aircleanprojectback/restapi/car/entity/Car.java
  src/main/java/aircleanprojectback/restapi/member/controller/HumanResourceController.java
  src/main/java/aircleanprojectback/restapi/member/dto/BranchDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/DriverDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/MemberAndDriverDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/MemberDTO.java
  src/main/java/aircleanprojectback/restapi/member/entity/Carpage.java
  src/main/java/aircleanprojectback/restapi/member/entity/Driver.java
  src/main/java/aircleanprojectback/restapi/member/entity/DriverAndCar.java
  src/main/java/aircleanprojectback/restapi/member/entity/MemberAndDriver.java
  src/main/java/aircleanprojectback/restapi/member/repository/DriverRepository.java
  src/main/java/aircleanprojectback/restapi/member/repository/MemberAndDriverRepository.java
  src/main/java/aircleanprojectback/restapi/member/repository/MembersAndEmployeeRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/HumanResourceService.java
Labels: ✨Feature

#131 [FEATURE]지점장페이지/ 보고서조회 - 지출보고서 수정, 삭제
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
  src/main/java/aircleanprojectback/restapi/report/service/ExpenseService.java
Labels: ✨Feature, :page_with_curl: DB, 📫API

#132 [FEATURE] 지점장페이지/ 보고서조회 - 시설물수리보고서 수정/ 삭제
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
Labels: ✨Feature, :page_with_curl: DB, 📫API

#133 [feature] driver
  src/main/java/aircleanprojectback/restapi/member/controller/HumanResourceController.java
  src/main/java/aircleanprojectback/restapi/member/dto/DriverAndCarDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/MemberAndDriverDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/MembersAndOwnerDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/RegistBranchManagerDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/RegistDTO.java
  src/main/java/aircleanprojectback/restapi/member/entity/Carpage.java
  src/main/java/aircleanprojectback/restapi/member/entity/DriverAndCar.java
  src/main/java/aircleanprojectback/restapi/member/repository/DriverAndCarRepository.java
  src/main/java/aircleanprojectback/restapi/member/repository/MemberAndDriverRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/HumanResourceService.java
Labels: ✨Feature

#139 [FEATURE]미배정기사 배정
  src/main/java/aircleanprojectback/restapi/car/controller/CarController.java
  src/main/java/aircleanprojectback/restapi/car/dto/DriverDTO.java
  src/main/java/aircleanprojectback/restapi/car/dto/MemberNameAndDriverDTO.java
  src/main/java/aircleanprojectback/restapi/car/entity/Driver.java
  src/main/java/aircleanprojectback/restapi/car/entity/MemberNameAndDriver.java
  src/main/java/aircleanprojectback/restapi/car/repository/CarRepository.java
  src/main/java/aircleanprojectback/restapi/car/repository/DriverRepository.java
  src/main/java/aircleanprojectback/restapi/car/repository/MemberNameAndDriverRepository.java
  src/main/java/aircleanprojectback/restapi/car/service/CarService.java
Labels: 📫API

#142 [FEATURE] 보고서관리 - 페이징 처리
  src/main/java/aircleanprojectback/restapi/car/service/CarService.java
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
  src/main/java/aircleanprojectback/restapi/report/controller/VehicleRepairController.java
  src/main/java/aircleanprojectback/restapi/report/dto/ExpenseDTO.java
  src/main/java/aircleanprojectback/restapi/report/repository/BranchSalesRepository.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
  src/main/java/aircleanprojectback/restapi/report/service/ExpenseService.java
  src/main/java/aircleanprojectback/restapi/report/service/RepairService.java
  src/main/java/aircleanprojectback/restapi/report/service/VehicleRepairService.java
  src/main/resources/static/memberimgs/null.
  src/main/resources/static/memberimgs/null.jpeg
  src/main/resources/static/memberimgs/null.png
Labels: ✨Feature, 📫API

#163 [FEATURE]보고서관리 - 승인, 반려 업데이트
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
  src/main/java/aircleanprojectback/restapi/report/controller/VehicleRepairController.java
  src/main/java/aircleanprojectback/restapi/report/dto/BranchSalesDTO.java
  src/main/java/aircleanprojectback/restapi/report/dto/ExpenseDTO.java
  src/main/java/aircleanprojectback/restapi/report/dto/RepairDTO.java
  src/main/java/aircleanprojectback/restapi/report/dto/VehicleRepairDTO.java
  src/main/java/aircleanprojectback/restapi/report/entity/BranchSales.java
  src/main/java/aircleanprojectback/restapi/report/entity/Expense.java
  src/main/java/aircleanprojectback/restapi/report/entity/Repair.java
  src/main/java/aircleanprojectback/restapi/report/entity/VehicleRepair.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
  src/main/java/aircleanprojectback/restapi/report/service/ExpenseService.java
  src/main/java/aircleanprojectback/restapi/report/service/RepairService.java
  src/main/java/aircleanprojectback/restapi/report/service/VehicleRepairService.java
Labels: ✨Feature, :page_with_curl: DB, 📫API

#178 [FEATURE]관리자페이지- 보고서사진 추가
  src/main/resources/application.yml
  src/main/resources/static/memberimgs/vehicleReport.png
Labels: :page_with_curl: DB

#180 [FEATURE]지점장페이지/ 보고서양식 사진추가
  src/main/resources/static/memberimgs/b6b6aeea-2611-4e5e-abca-bdd2bac2af9a.png
  src/main/resources/static/memberimgs/branchSalesReports.png
  src/main/resources/static/memberimgs/expenseReport.png
  src/main/resources/static/memberimgs/repairReports.png
Labels: :page_with_curl: DB

#182 [feature] 시설물 시간 localstorage에 저장후 관련 데이터 db 에 저장
  src/main/java/aircleanprojectback/restapi/facility/controller/FacilityController.java
  src/main/resources/application.yml
Labels: ✨Feature

#184 [feature] 시설물 중간 커밋
  src/main/java/aircleanprojectback/restapi/facility/controller/FacilityController.java
  src/main/java/aircleanprojectback/restapi/facility/service/FacilityService.java
  src/main/java/aircleanprojectback/restapi/laundry/dto/LaundryDTO.java
  src/main/java/aircleanprojectback/restapi/laundry/entity/Laundry.java
  src/main/java/aircleanprojectback/restapi/laundry/repository/LaundryRepository.java
  src/main/java/aircleanprojectback/restapi/laundry/service/GptApiService.java
  src/main/java/aircleanprojectback/restapi/laundry/service/RegistrationService.java
Labels: ✔Test
