Repository Air-Clean/airclean-spring, pull requests merged in 2024-07, with the labels that each got.

#20 [24.07.16] 보고서 dto, entity
  src/main/java/aircleanprojectback/restapi/auth/filter/CustomAuthenticationFilter.java
  src/main/java/aircleanprojectback/restapi/auth/filter/JwtAuthorizationFilter.java
  src/main/java/aircleanprojectback/restapi/common/dto/ResponseDTO.java
  src/main/java/aircleanprojectback/restapi/member/controller/MemberController.java
  src/main/java/aircleanprojectback/restapi/member/dto/MemberDTO.java
  src/main/java/aircleanprojectback/restapi/member/entity/Members.java
  src/main/java/aircleanprojectback/restapi/member/repository/MemberRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/MemberService.java
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
  src/main/java/aircleanprojectback/restapi/report/controller/VehicleRepairController.java
  src/main/java/aircleanprojectback/restapi/report/dto/BranchSalesDTO.java
  src/main/java/aircleanprojectback/restapi/report/dto/ExpenseDTO.java
  src/main/java/aircleanprojectback/restapi/report/dto/RepairDTO.java
  src/main/java/aircleanprojectback/restapi/report/dto/VehicleRepairDTO.java
  src/main/java/aircleanprojectback/restapi/report/entity/BranchSales.java
  src/main/java/aircleanprojectback/restapi/report/entity/Expense.java
  src/main/java/aircleanprojectback/restapi/report/entity/Repair.java
  src/main/java/aircleanprojectback/restapi/report/entity/VehicleRepair.java
Labels: feature

#22 [FEATURE] 헤더
  src/main/java/aircleanprojectback/restapi/mainpage/model/entity/Expenditure.java
  src/main/java/aircleanprojectback/restapi/mainpage/model/entity/Revenue.java
  src/main/java/aircleanprojectback/restapi/mainpage/model/entity/TotalRevenue.java
  src/main/java/aircleanprojectback/restapi/member/controller/HumanResourceController.java
  src/main/java/aircleanprojectback/restapi/member/controller/MemberController.java
  src/main/java/aircleanprojectback/restapi/member/dto/MailDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/MemberDTO.java
  src/main/java/aircleanprojectback/restapi/member/entity/Branch.java
  src/main/java/aircleanprojectback/restapi/member/entity/Driver.java
  src/main/java/aircleanprojectback/restapi/member/entity/Employee.java
  src/main/java/aircleanprojectback/restapi/member/entity/MemberRole.java
  src/main/java/aircleanprojectback/restapi/member/entity/Members.java
  src/main/java/aircleanprojectback/restapi/member/repository/MemberRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/MailService.java
  src/main/java/aircleanprojectback/restapi/member/service/MemberService.java
  src/main/resources/application.yml
Labels: feature

#43 Feature/human resource
  src/main/java/aircleanprojectback/restapi/auth/config/WebConfig.java
  src/main/java/aircleanprojectback/restapi/auth/config/WebSecurityConfig.java
  src/main/java/aircleanprojectback/restapi/auth/filter/HeaderFilter.java
  src/main/java/aircleanprojectback/restapi/member/controller/HumanResourceController.java
  src/main/java/aircleanprojectback/restapi/member/entity/Members.java
  src/main/java/aircleanprojectback/restapi/member/repository/MemberRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/HumanResourceService.java
  src/main/java/aircleanprojectback/restapi/stock/entity/EmployeeCode.java
  src/main/resources/application.yml
  src/main/resources/static/memberimgs/1.PNG
  src/main/resources/static/memberimgs/10.PNG
  src/main/resources/static/memberimgs/11.PNG
  src/main/resources/static/memberimgs/12.PNG
  src/main/resources/static/memberimgs/13.PNG
  src/main/resources/static/memberimgs/14.PNG
  src/main/resources/static/memberimgs/15.PNG
  src/main/resources/static/memberimgs/16.PNG
  src/main/resources/static/memberimgs/17.PNG
  src/main/resources/static/memberimgs/18.PNG
  src/main/resources/static/memberimgs/19.PNG
  src/main/resources/static/memberimgs/2.PNG
  src/main/resources/static/memberimgs/20.PNG
  src/main/resources/static/memberimgs/21.PNG
  src/main/resources/static/memberimgs/3.PNG
  src/main/resources/static/memberimgs/4.PNG
  src/main/resources/static/memberimgs/5.PNG
  src/main/resources/static/memberimgs/6.PNG
  src/main/resources/static/memberimgs/7.PNG
  src/main/resources/static/memberimgs/8.PNG
  src/main/resources/static/memberimgs/9.PNG
  src/main/resources/static/memberimgs/hong.png
Labels: feature

#55 지출보고서 - 상세보기
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/repository/ExpenseRepository.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
  src/main/java/aircleanprojectback/restapi/report/service/ExpenseService.java
Labels: feature

#75 [Feature] 재고내역조회 api 생성
  build.gradle
  src/main/java/aircleanprojectback/restapi/stock/controller/StockController.java
  src/main/java/aircleanprojectback/restapi/stock/dto/HeadStockApplicationDTO.java
  src/main/java/aircleanprojectback/restapi/stock/dto/HeadStockUpdate.java
  src/main/java/aircleanprojectback/restapi/stock/dto/LaundryPartAndManagementDTO.java
  src/main/java/aircleanprojectback/restapi/stock/dto/LaundrySupplyAndManagementDTO.java
  src/main/java/aircleanprojectback/restapi/stock/entity/HeadStockApplication.java
  src/main/java/aircleanprojectback/restapi/stock/entity/LaundryPartAndManagement.java
  src/main/java/aircleanprojectback/restapi/stock/entity/LaundrySupplyAndManagement.java
  src/main/java/aircleanprojectback/restapi/stock/entity/LocationCodeAndBranchStockApplication.java
  src/main/java/aircleanprojectback/restapi/stock/entity/LocationCodeAndHeadStockApplication.java
  src/main/java/aircleanprojectback/restapi/stock/repository/HeadStockApplicationRepository.java
  src/main/java/aircleanprojectback/restapi/stock/repository/LaundryPartManagementRepository.java
  src/main/java/aircleanprojectback/restapi/stock/repository/LaundrySupplyManagementRepository.java
  src/main/java/aircleanprojectback/restapi/stock/service/StockService.java
Labels: feature

#78 시설물수리보고서 세부조회
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
  src/main/java/aircleanprojectback/restapi/report/repository/RepairRepository.java
  src/main/java/aircleanprojectback/restapi/report/repository/VehicleRepairRepository.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
  src/main/java/aircleanprojectback/restapi/report/service/RepairService.java
Labels: feature

#81 [FEATURE]보고서관리 - 보고서조회 - 매출보고서 상세조회 시 승인/ 반려
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/entity/BranchSales.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
  src/main/java/aircleanprojectback/restapi/report/service/ExpenseService.java
  uploads/65fc6d67da52452891710fef01fb9eee.png
Labels: feature

#83 [feature] stockHistory getMappig api 수정
  src/main/java/aircleanprojectback/restapi/stock/dto/HeadStockApplicationDTO.java
Labels: feature

#89 [FEATURE] 보고서관리 - 승인/반려
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
  src/main/java/aircleanprojectback/restapi/report/controller/VehicleRepairController.java
  src/main/java/aircleanprojectback/restapi/report/dto/CarMembersDTO.java
  src/main/java/aircleanprojectback/restapi/report/dto/VehicleRepairDTO.java
  src/main/java/aircleanprojectback/restapi/report/entity/CarMembers.java
  src/main/java/aircleanprojectback/restapi/report/entity/Expense.java
  src/main/java/aircleanprojectback/restapi/report/entity/VehicleRepair.java
  src/main/java/aircleanprojectback/restapi/report/repository/CarMembersRepository.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
  src/main/java/aircleanprojectback/restapi/report/service/CarMembersService.java
  src/main/java/aircleanprojectback/restapi/report/service/ExpenseService.java
  src/main/java/aircleanprojectback/restapi/report/service/RepairService.java
  src/main/java/aircleanprojectback/restapi/report/service/VehicleRepairService.java
Labels: ✨Feature, 📫API

#98 [FEATURE] 보고서작성- 차량수리보고서 등록
  src/main/java/aircleanprojectback/restapi/report/controller/BranchSalesController.java
  src/main/java/aircleanprojectback/restapi/report/controller/VehicleRepairController.java
  src/main/java/aircleanprojectback/restapi/report/repository/BranchSalesRepository.java
  src/main/java/aircleanprojectback/restapi/report/service/BranchSalesService.java
  src/main/java/aircleanprojectback/restapi/report/service/VehicleRepairService.java
  src/main/resources/static/memberimgs/566156e094534c4f8a552823aa053eb1.jpeg
  src/main/resources/static/memberimgs/9949b9426ed34be39accae50a6840ae4.jpeg
Labels: ✨Feature, :page_with_curl: DB, 📫API

#99 [DB] branch entity 교체
  src/main/java/aircleanprojectback/restapi/branch/controller/BranchController.java
  src/main/java/aircleanprojectback/restapi/branch/repository/BranchRepository.java
  src/main/java/aircleanprojectback/restapi/branch/service/BranchService.java
  src/main/java/aircleanprojectback/restapi/member/controller/HumanResourceController.java
  src/main/java/aircleanprojectback/restapi/member/dto/BranchDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/BranchOwnerDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/MemberDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/MembersAndOwnerDTO.java
  src/main/java/aircleanprojectback/restapi/member/dto/RegistBranchManagerDTO.java
  src/main/java/aircleanprojectback/restapi/member/entity/Branch.java
  src/main/java/aircleanprojectback/restapi/member/entity/BranchAndMembers.java
  src/main/java/aircleanprojectback/restapi/member/entity/BranchOwner.java
  src/main/java/aircleanprojectback/restapi/member/entity/Members.java
  src/main/java/aircleanprojectback/restapi/member/entity/MembersAndOwner.java
  src/main/java/aircleanprojectback/restapi/member/repository/BranchAndMembersRepository.java
  src/main/java/aircleanprojectback/restapi/member/repository/MemberRepository.java
  src/main/java/aircleanprojectback/restapi/member/repository/OwnerRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/HumanResourceService.java
  src/main/resources/static/memberimgs/bc7fee8973e34718b3ba7ddb5b2c4010.png
  src/main/resources/static/memberimgs/e10a94d90c92494189078345f80bb3f9.png
Labels: :page_with_curl: DB

#107 [feature] branch api 생성
  src/main/java/aircleanprojectback/restapi/branch/controller/BranchController.java
  src/main/java/aircleanprojectback/restapi/branch/service/BranchService.java
  src/main/java/aircleanprojectback/restapi/branch/service/BranchService1.java
  src/main/java/aircleanprojectback/restapi/member/controller/HumanResourceController.java
  src/main/java/aircleanprojectback/restapi/member/dto/DriverDTO.java
  src/main/java/aircleanprojectback/restapi/member/entity/CarForMember.java
  src/main/java/aircleanprojectback/restapi/member/entity/Driver.java
  src/main/java/aircleanprojectback/restapi/member/repository/DriverRepository.java
  src/main/java/aircleanprojectback/restapi/member/repository/OwnerRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/HumanResourceService.java
Labels: 📫API

#109 [FEATURE] 지점장페이지/ 보고서양식 - 지출보고서 등록
  src/main/java/aircleanprojectback/restapi/report/controller/ExpenseController.java
  src/main/java/aircleanprojectback/restapi/report/entity/Expense.java
  src/main/java/aircleanprojectback/restapi/report/service/ExpenseService.java
Labels: ✨Feature, :page_with_curl: DB, 📫API, 🎨Html&css

#114 [FEATURE] 지점장페이지/ 보고서양식 - 시설물수리 보고서 등록 API 연동
  src/main/java/aircleanprojectback/restapi/report/controller/RepairController.java
  src/main/java/aircleanprojectback/restapi/report/dto/RepairDTO.java
  src/main/java/aircleanprojectback/restapi/report/entity/Repair.java
  src/main/java/aircleanprojectback/restapi/report/service/RepairService.java
  src/main/resources/static/memberimgs/null.png
Labels: ✨Feature, :page_with_curl: DB, 📫API

#115 [feature] branch 페이지 관련 controller 생성
  src/main/java/aircleanprojectback/restapi/branch/controller/BranchController1.java
  src/main/java/aircleanprojectback/restapi/branch/dto/FacilityDTO.java
  src/main/java/aircleanprojectback/restapi/branch/dto/FacilityDetailDTO.java
  src/main/java/aircleanprojectback/restapi/branch/repository/BranchRepository.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/controller/BranchController.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/dao/BranchPageRepository.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/dao/FacilityDetailRepository.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/dto/BranchOwnerPageDTO.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/dto/BranchPageDTO.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/dto/MembersPageDTO.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/entity/BranchOwnerPage.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/entity/BranchPage.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/entity/MembersPage.java
  src/main/java/aircleanprojectback/restapi/branchOrigin/service/BranchService.java
  src/main/java/aircleanprojectback/restapi/member/entity/Members.java
  src/main/java/aircleanprojectback/restapi/member/repository/MemberRepository.java
  src/main/java/aircleanprojectback/restapi/member/repository/OwnerRepository.java
  src/main/java/aircleanprojectback/restapi/member/service/HumanResourceService.java
Labels: ✨Feature
